id: P000501
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD105834
  title: མི་ཡུལ་གྱི་གཏམ་རྒྱུད་།
  author: ''
  volumes:
    1ae778aba0a043088761b879fa47d38c:
      image_group_id: I1PD105836
      title: Volume 1 of mi yul gyi gtam rgyud
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
